### ISSUE TITLE
Arrumar o nome da fila

### ISSUE THREAD

**Issue by ljsomm** [projeto-sinuka/infrastructure#19]
Precisamos colocar o mesmo nome do SQS que esta na arquitetura:

![image](https://github.com/user-attachments/assets/b4b8d1ac-f1db-4d31-9f7b-19b60e866e78)

Atualmente está:

`name                    = "SQS_Failure_Alarm"`

No arquivo: `/sqs.tf`

**Comment by ljsomm** [comment]
Nova branch pra ser criada: `fix/19-arrumar-o-nome-da-fila`

**Comment by ljsomm** [comment]
Nome da fila corrigido: sqs-failure-cases

**Comment by GustavoTQ4** [comment]
![image](https://github.com/user-attachments/assets/6f13cfe4-fc54-4c79-9e33-644046b40f92)
